In [1]:
import numpy as np
import sys

In [9]:
x=list(range(2000))
y=np.arange(2000)
print("memory size(bytes) of list with 2000 element:",sys.getsizeof(x))
print("memory size(bytes) of array with 2000 element:",sys.getsizeof(y))

memory size(bytes) of list with 2000 element: 16056
memory size(bytes) of array with 2000 element: 8104


In [10]:
a=np.zeros(5)
print(a)

[0. 0. 0. 0. 0.]


In [11]:
a[-1]=50
print(a)

[ 0.  0.  0.  0. 50.]


In [12]:
a=np.zeros(5, dtype=np.int32)   #size,dtype 
print(a)

[0 0 0 0 0]


In [14]:
a=np.ones(5, dtype=np.int32)
print(a)

[1 1 1 1 1]


In [18]:
a=np.full(5,100)  #size, intial_value
print(a)

[100 100 100 100 100]


In [20]:
a=np.array([50,100,128,129],dtype=np.int8)
print(a)

[  50  100 -128 -127]


In [21]:
a=np.array([50,100,128,-129],dtype=np.int8)
print(a)                                          #round robin fassion

[  50  100 -128  127]


In [25]:
a=np.array([50,100,128,129,255,257],dtype=np.uint8)
print(a)                                         #0-255 positive value

[ 50 100 128 129 255   1]


In [32]:
a=np.linspace(10,20,5) #start,end,how many element u want
print(a)

[10.  12.5 15.  17.5 20. ]


In [33]:
a=np.linspace(10,100)     #by default size will be consider 50
print(a)
print(len(a))

[ 10.          11.83673469  13.67346939  15.51020408  17.34693878
  19.18367347  21.02040816  22.85714286  24.69387755  26.53061224
  28.36734694  30.20408163  32.04081633  33.87755102  35.71428571
  37.55102041  39.3877551   41.2244898   43.06122449  44.89795918
  46.73469388  48.57142857  50.40816327  52.24489796  54.08163265
  55.91836735  57.75510204  59.59183673  61.42857143  63.26530612
  65.10204082  66.93877551  68.7755102   70.6122449   72.44897959
  74.28571429  76.12244898  77.95918367  79.79591837  81.63265306
  83.46938776  85.30612245  87.14285714  88.97959184  90.81632653
  92.65306122  94.48979592  96.32653061  98.16326531 100.        ]
50


In [46]:
a=np.random.randint(1,10,5) #low,high,size 
print(a)

[2 1 8 5 4]


In [49]:
a=np.random.uniform(1,10,5) #low,high,size
print(a)

[2.44964292 1.81117138 8.42206366 5.40464172 6.12162898]


In [51]:
a=np.loadtxt("E:/e drive data/DATA Analystics RAJAT/text1.txt", delimiter="\n")
print(a)

[10. 20. 30. 40. 50.]


In [52]:
a=np.loadtxt("E:/e drive data/DATA Analystics RAJAT/text2.txt", delimiter=",")
print(a)

[10. 20. 30. 40. 50.]


In [53]:
a=np.random.randint(1,10,5) #low,high,size 
print(a)

[9 3 3 8 2]


In [54]:
np.savetxt("E:/e drive data/DATA Analystics RAJAT/text3.txt",a,newline=",",fmt="%d")

In [5]:
a=np.array([[1,2],[3,4],[5,6]])
print(a)
print(type(a), a.dtype)
print(a.ndim)  # which type of array
print(a.shape)

[[1 2]
 [3 4]
 [5 6]]
<class 'numpy.ndarray'> int32
2
(3, 2)


In [6]:
a=np.array([[1,2],[3,4],[5,6,7]])
print(a)
print(type(a), a.dtype)
print(a.ndim)  # which type of array
print(a.shape)

[list([1, 2]) list([3, 4]) list([5, 6, 7])]
<class 'numpy.ndarray'> object
1
(3,)


C:\Users\india\AppData\Local\Temp\ipykernel_4696\1521591614.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a=np.array([[1,2],[3,4],[5,6,7]])


In [7]:
a=np.zeros((4,5)) #row,column
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [8]:
a=np.ones((5,4)) #r, c
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [9]:
a=np.full((3,3),10) #(r,c),initial_value
print(a)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [18]:
a=np.random.randint(1,10,(3,4))  #low,high,(r,c)
print(a)

[[7 3 4 2]
 [2 8 8 1]
 [8 3 6 2]]


In [20]:
a=np.random.uniform(1,10,(3,4))  #low,high,(r,c)
print(a)

[[8.31927445 9.97687974 7.22273378 2.4303106 ]
 [2.27124233 5.21637371 5.28076282 2.64739209]
 [4.32899019 8.89971414 7.09866417 4.41987757]]


In [21]:
a=np.eye(3,3)  #reture identity metrix  of r,c
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [31]:
a=np.eye(5,3)  #reture identity metrix  of r,c
print(a)
print(a.ndim)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]
2


### 3D Array

In [32]:
a=np.random.randint(1,10,(4,3,3)) #low,high,(size,r,c)
print(a)
print(a.ndim)

[[[3 6 4]
  [2 5 7]
  [1 4 3]]

 [[6 7 1]
  [5 9 3]
  [8 5 2]]

 [[6 3 3]
  [3 8 8]
  [6 7 1]]

 [[4 4 4]
  [9 8 4]
  [1 8 2]]]
3


In [33]:
a=np.zeros((2,3,4)) #size,row,column
print(a)
print(a.ndim)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
3


### 4D Array

In [36]:
a=np.random.randint(1,10,(3,4,3,3)) #low,high(size_of_4d_array,size_of_3d_array,r,c)
#print(a.ndim)
print(a)

[[[[1 5 3]
   [2 1 6]
   [3 7 1]]

  [[9 9 7]
   [8 7 5]
   [4 2 6]]

  [[3 4 7]
   [7 9 4]
   [6 7 4]]

  [[5 1 9]
   [7 9 5]
   [7 2 8]]]


 [[[1 5 4]
   [8 4 9]
   [6 4 5]]

  [[4 7 6]
   [4 3 7]
   [9 6 8]]

  [[9 1 2]
   [8 4 4]
   [2 6 6]]

  [[6 7 6]
   [5 6 8]
   [5 9 8]]]


 [[[3 7 1]
   [1 8 1]
   [3 7 1]]

  [[6 3 8]
   [7 4 3]
   [4 6 4]]

  [[9 2 7]
   [8 2 9]
   [1 3 7]]

  [[1 2 3]
   [8 8 8]
   [9 7 6]]]]


In [37]:
a=np.zeros((2,4,3,4)) #size_of_4d,size_of_3d,row,column
print(a)
print(a.ndim)

[[[[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]]


 [[[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]]]
4


#### transform dimention to each other
 * flatten() > any dimention transfer to 1d
 * reshape()
 * resize()

In [39]:
a=np.random.randint(1,10,(3,3))
print(a)

[[1 3 2]
 [6 1 1]
 [9 8 9]]


In [42]:
b=a.flatten() #row major order
print(b)      #flatten that mathor a new coppy of 1D array in raw major order

[1 3 2 6 1 1 9 8 9]


In [43]:
print(a)

[[1 3 2]
 [6 1 1]
 [9 8 9]]


In [44]:
c=a.flatten(order="F") #column major order
print(c)

[1 6 9 3 1 8 2 1 9]


In [1]:
import numpy as np

#### Reshape > convert into more than one dimention

In [4]:
a=np.arange(12)
print(a)

b=np.random.randint(1,10,(3,4))
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[8 6 3 7]
 [8 2 5 9]
 [2 4 4 3]]


In [5]:
a.reshape(4,3)  #r,c

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [6]:
a.reshape(6,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [7]:
a.reshape(2,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [8]:
a.reshape(3,-1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [9]:
a.reshape(4,-1)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [10]:
a.reshape(-1,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [11]:
a.reshape(-1,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [12]:
a.reshape(2,3,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [13]:
a.reshape(1,4,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]])

In [14]:
print(b)

[[8 6 3 7]
 [8 2 5 9]
 [2 4 4 3]]


In [19]:
b.reshape(4,3,order='F')  #column major order > read column wise and write column wise

array([[8, 2, 4],
       [8, 4, 7],
       [2, 3, 9],
       [6, 5, 3]])

In [20]:
a.reshape(4,3,order='c') 

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

#### Resize

In [22]:
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [24]:
a.resize(3,4) #change in the existing array
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [25]:
a.resize(4,-1)

ValueError: negative dimensions not allowed

In [26]:
a.resize(5,3)

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

In [27]:
a.resize(5,3,refcheck=False)

In [28]:
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [ 0  0  0]]


In [29]:
 a.resize(5,2,refcheck=False)

In [30]:
print(a)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [2]:
import numpy as np
a=np.arange(12)
print(a)

b=np.random.randint(1,10,(3,4))
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[9 9 2 5]
 [2 1 5 3]
 [4 1 1 8]]


In [4]:
print(a.sum())
print(np.sum(a))
print(b.sum())
print(b.sum(axis=1)) #row wise sum
print(b.sum(axis=0)) #column wise sum 

66
66
50
[25 11 14]
[15 11  8 16]


In [8]:
print(a.mean())
print(b.mean())
print(b.mean(axis=1)) #row wise mean
print(b.mean(axis=0)) #column wise mean

5.5
4.166666666666667
[6.25 2.75 3.5 ]
[5.         3.66666667 2.66666667 5.33333333]


In [12]:
print(np.median(a))
print(np.median(b))
print(np.median(b,axis=1)) #row wise median
print(np.median(b,axis=0)) #column wise median

5.5
3.5
[7.  2.5 2.5]
[4. 1. 2. 5.]


In [15]:
print(np.sum([1,2,3]))

6


In [16]:
print(np.sum((1,2,3)))

6


In [18]:
np.sum(range(10))

45

In [29]:
print(a.min()) #method
print(np.min(a)) #function
print(np.min(b))
print(np.min(b,axis=1))
print(np.min(b,axis=0))


0
0
1
[2 1 1]
[2 1 1 3]


In [31]:
print(a.max()) #method
print(np.max(a)) #function
print(np.max(b))
print(np.max(b,axis=1))
print(np.max(b,axis=0))

11
11
9
[9 5 8]
[9 9 5 8]


In [37]:
a=np.random.randint(1,10,10)
print(a)

[8 4 5 7 5 4 9 2 5 2]


In [39]:
print(np.min(a))
print(np.argmin(a)) #return index of min element

2
7


In [40]:
print(np.max(a))
print(np.argmax(a)) #return index of max element

9
6


In [41]:
#print(b)

[[9 9 2 5]
 [2 1 5 3]
 [4 1 1 8]]


In [47]:
#arg- return index position of value

print(b.argmin()) #firstly 2D array will be flatten and than apply #arg method
print(b.argmax())
print(b.argmax(axis=1))
print(b.argmax(axis=0))

5
0
[0 2 3]
[0 0 1 2]


#### Broadcasting

In [48]:
print(a)

[8 4 5 7 5 4 9 2 5 2]


In [50]:
x=[8,4,5,7,5,4,9,2,5,2]

In [51]:
y=[]
for i in x:
    y.append(i+2)
print(y)

[10, 6, 7, 9, 7, 6, 11, 4, 7, 4]


In [63]:
a1=a+2
print(a1)
a1

[10  6  7  9  7  6 11  4  7  4]


array([10,  6,  7,  9,  7,  6, 11,  4,  7,  4])

In [60]:
#x=[10000,20000,15000,20000,30000]
#y=[]
#for i in x:
#    y.append(i+i*0.05)
#print(y)

In [64]:
np.square(a)

array([64, 16, 25, 49, 25, 16, 81,  4, 25,  4], dtype=int32)

In [65]:
np.sqrt(a)

array([2.82842712, 2.        , 2.23606798, 2.64575131, 2.23606798,
       2.        , 3.        , 1.41421356, 2.23606798, 1.41421356])

In [66]:
np.log(a) #base e

array([2.07944154, 1.38629436, 1.60943791, 1.94591015, 1.60943791,
       1.38629436, 2.19722458, 0.69314718, 1.60943791, 0.69314718])

In [67]:
np.log10(a) #base 10

array([0.90308999, 0.60205999, 0.69897   , 0.84509804, 0.69897   ,
       0.60205999, 0.95424251, 0.30103   , 0.69897   , 0.30103   ])

In [1]:
 import numpy as np

In [2]:
a=np.random.randint(1,10,10)
b=np.random.randint(1,10,10)
print(a)
print(b)

[2 4 4 5 3 9 1 6 3 9]
[6 1 8 7 5 7 7 2 3 8]


In [4]:
c=a+b
print(c)

[ 8  5 12 12  8 16  8  8  6 17]


In [5]:
a*b

array([12,  4, 32, 35, 15, 63,  7, 12,  9, 72])

In [6]:
a/b

array([0.33333333, 4.        , 0.5       , 0.71428571, 0.6       ,
       1.28571429, 0.14285714, 3.        , 1.        , 1.125     ])

In [7]:
a**b

array([      64,        4,    65536,    78125,      243,  4782969,
              1,       36,       27, 43046721], dtype=int32)

In [8]:
a//b

array([0, 4, 0, 0, 0, 1, 0, 3, 1, 1], dtype=int32)

In [9]:
a%b

array([2, 0, 4, 5, 3, 2, 1, 0, 0, 1], dtype=int32)

In [18]:
a=np.random.randint(1,10,10)
b=np.random.randint(1,10,11)
print(a)
print(b)

[8 1 5 9 1 3 4 5 2 2]
[9 7 1 4 8 6 9 3 4 4 6]


In [11]:
a+b

ValueError: operands could not be broadcast together with shapes (10,) (11,) 

In [23]:
print(a)

[8 1 5 9 1 3 4 5 2 2]


In [27]:
print(sorted(a))
print(type(a))
print(a.dtype)

[1, 1, 2, 2, 3, 4, 5, 5, 8, 9]
<class 'numpy.ndarray'>
int32


In [29]:
b.sort()
print(b)
print(type(b))
print(b.dtype)

[1 3 4 4 4 6 6 7 8 9 9]
<class 'numpy.ndarray'>
int32


In [30]:
print(a)
print(b)

[8 1 5 9 1 3 4 5 2 2]
[1 3 4 4 4 6 6 7 8 9 9]


In [34]:
print(5 in a)
print(9 in b)
print(7 in a)

True
True
False


In [37]:
#where
print(np.where(a==4)) #return index position of element that full fill the condition
print(np.where(b==9))
print(np.where(a==2))

(array([6], dtype=int64),)
(array([ 9, 10], dtype=int64),)
(array([8, 9], dtype=int64),)


In [40]:
print(np.where(a>5))
print(np.where(b<4))
print(np.where(b<=6))

(array([0, 3], dtype=int64),)
(array([0, 1], dtype=int64),)
(array([0, 1, 2, 3, 4, 5, 6], dtype=int64),)


In [42]:
print(a)
print(b)

[8 1 5 9 1 3 4 5 2 2]
[1 3 4 4 4 6 6 7 8 9 9]


In [43]:
#boolean/conditional slicing > filter the element based on given condition

print(a[a>5])
print(a[a<5])

[8 9]
[1 1 3 4 2 2]


In [46]:
print(b[b%2==0]) #even element filter
print(b[b%2==1])


[4 4 4 6 6 8]
[1 3 7 9 9]


In [47]:
c=b[b%2==0]
c[c>5]


array([6, 6, 8])

In [53]:
#b[b%2==0 and b>5] #error
#[b%2==0 & b>5] #error
b[(b%2==0) & (b>5)]

array([6, 6, 8])

In [55]:
b[(b%2==0) | (b<5)]

array([1, 3, 4, 4, 4, 6, 6, 8])

In [56]:
marks=np.random.uniform(40,100,20)
print(marks)

[70.59136987 48.7140951  54.32883192 97.4202302  53.13473688 66.21529544
 61.80686747 70.55041031 80.94111119 94.57178753 78.95643565 42.71646358
 85.43070285 54.59047605 47.74461407 56.80911358 53.54203619 56.19714684
 65.61354628 44.6803606 ]


In [57]:
np.where(marks>=60)

(array([ 0,  3,  5,  6,  7,  8,  9, 10, 12, 18], dtype=int64),)

In [61]:
marks[marks>=60]

array([70.59136987, 97.4202302 , 66.21529544, 61.80686747, 70.55041031,
       80.94111119, 94.57178753, 78.95643565, 85.43070285, 65.61354628])

In [62]:
a=np.random.randint(1,10,10)
b=np.random.randint(1,10,10)

In [63]:
np.where(a==b)

(array([0, 7], dtype=int64),)

In [64]:
print(a)
print(b)

[4 8 3 2 9 2 7 4 7 5]
[4 4 2 3 8 7 2 4 4 6]


In [65]:
np.where(a>b)

(array([1, 2, 4, 6, 8], dtype=int64),)

In [8]:
import numpy as np

In [9]:
a=np.random.randint(1,6,(3,3))
print(a)

[[3 4 1]
 [2 3 3]
 [3 1 2]]


In [10]:
print(np.transpose(a)) #function

[[3 2 3]
 [4 3 1]
 [1 3 2]]


In [11]:
print(a.transpose()) #method

[[3 2 3]
 [4 3 1]
 [1 3 2]]


In [12]:
print(a.T)

[[3 2 3]
 [4 3 1]
 [1 3 2]]


In [13]:
b=np.random.randint(1,6,(3,3))

In [14]:
print(a)
print('\n')
print(b)

[[3 4 1]
 [2 3 3]
 [3 1 2]]


[[5 5 3]
 [3 3 2]
 [2 1 1]]


In [15]:
a*b  #element be element multiplication

array([[15, 20,  3],
       [ 6,  9,  6],
       [ 6,  1,  2]])

In [16]:
#dot
np.dot(a,b)

array([[29, 28, 18],
       [25, 22, 15],
       [22, 20, 13]])

In [22]:
a@b

array([[37, 50],
       [48, 68],
       [73, 95]])

In [23]:
b@a

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

In [18]:
a=np.random.randint(1,10,(3,3))
b=np.random.randint(1,10,(3,2))

In [19]:
print(a)
print(b)

[[3 7 3]
 [7 6 3]
 [9 4 6]]
[[3 5]
 [1 2]
 [7 7]]


In [20]:
a@b

array([[37, 50],
       [48, 68],
       [73, 95]])

In [25]:
b.T@a

array([[79, 55, 54],
       [92, 75, 63]])

In [26]:
print(a)

[[3 7 3]
 [7 6 3]
 [9 4 6]]


In [28]:
a=a.flatten()

In [29]:
print(a)

[3 7 3 7 6 3 9 4 6]


In [30]:
a[0]=8

In [31]:
print(a)

[8 7 3 7 6 3 9 4 6]


In [32]:
np.append(a,10)

array([ 8,  7,  3,  7,  6,  3,  9,  4,  6, 10])

In [33]:
print(a)

[8 7 3 7 6 3 9 4 6]


In [34]:
np.insert(a,1,10)

array([ 8, 10,  7,  3,  7,  6,  3,  9,  4,  6])

In [35]:
np.insert(a,0,[1,2,3])

array([1, 2, 3, 8, 7, 3, 7, 6, 3, 9, 4, 6])

In [36]:
np.delete(a,0)  #index position

array([7, 3, 7, 6, 3, 9, 4, 6])

In [37]:
print(a)
np.delete(a,[1,3,6])

[8 7 3 7 6 3 9 4 6]


array([8, 3, 6, 3, 4, 6])

In [53]:
a=np.random.randint(1,5,10)
print(a)

[1 2 4 3 3 4 4 1 4 1]


In [54]:
a[3]=0
print(a)

[1 2 4 0 3 4 4 1 4 1]


In [55]:
np.count_nonzero(a)

9

In [56]:
np.std(a)

1.4966629547095767

In [60]:
np.quantile(a,0.50)

2.5

In [61]:
np.quantile(a,[.25,.5,.75])

array([1. , 2.5, 4. ])

In [62]:
np.quantile(a,[.2,.5,.6])

array([1. , 2.5, 3.4])

In [63]:
np.quantile(a,[.15,.45,.85])

array([1.  , 2.05, 4.  ])