In [1]:
import statistics as stats

In [2]:
x = [2,3,4]
print(stats.mean(x))  # Arithmetic mean
print(stats.geometric_mean(x))
print(stats.harmonic_mean(x))

3
2.8844991406148166
2.769230769230769


In [3]:
y =(2,3,10)
print(stats.mean(y))
print(stats.geometric_mean(y))
print(stats.harmonic_mean(y))

5
3.9148676411688643
3.2142857142857144


In [4]:
x = [80,100,30]
print(stats.mean(x))
print(stats.harmonic_mean(x))

70
53.73134328358209


In [5]:
#mode
x = [10,20,"hello",10,"hello",10]
print(stats.mode(x))

10


In [6]:
x = [10,20,"hello",10,"hello",10,"hello"]
print(stats.mode(x))

10


In [7]:
x = [20,"hello",10,"hello",10,10,"hello"]
print(stats.mode(x))

hello


In [8]:
x = [10,20,"hello",10,"hello",10,"hello"]
print(stats.multimode(x))

[10, 'hello']


In [9]:
#median
x = [10,7,8,4,6,3,8]
sorted(x)

[3, 4, 6, 7, 8, 8, 10]

In [10]:
print(stats.median(x))

7


In [11]:
x = [10,7,8,4,6,3,8,9]
sorted(x)

[3, 4, 6, 7, 8, 8, 9, 10]

In [12]:
print(stats.median(x))

7.5


In [13]:
x = [10,7,8,4,6,3,8,9]
sorted(x)
print(stats.median_low(x))
print(stats.median_high(x))

7
8


In [14]:
import random
x = []
for i in range(50):
    x.append(random.randint(1,100))
print(x)

[37, 7, 38, 88, 38, 60, 67, 7, 26, 67, 79, 13, 42, 28, 97, 20, 23, 4, 66, 98, 64, 83, 70, 98, 16, 7, 99, 43, 30, 75, 83, 46, 17, 6, 90, 62, 45, 97, 96, 96, 40, 93, 65, 38, 67, 59, 49, 1, 39, 97]


In [15]:
print("median =",stats.median(x))
print("mean =",stats.mean(x))

median = 54.0
mean = 53.52


In [16]:
print(stats.quantiles(x))  # 25%, 50%, 75%

[27.5, 54.0, 83.0]


In [17]:
import statistics as stats

In [18]:
#Outlire/Anomaly
x = [1,2,5,3,6,3,2,5,3,-50,350]
#iqr(inter-quantile range)
q1,q2,q3 = stats.quantiles(x)

In [19]:
iqr = q3-q1
print(iqr)

3.0


In [20]:
lowbound = q1-1.5*iqr
highbound = q3+1.5*iqr
print(lowbound,highbound)

-2.5 9.5


In [21]:
for i in x:
    if(i<lowbound):
        print(i,"is low outlire")
    if(i>highbound):
        print(i,"is high outlire")

-50 is low outlire
350 is high outlire


In [22]:
import random
x = []
for i in range(50):
    x.append(random.randint(1,100))
print(x)

[23, 36, 9, 6, 85, 77, 81, 12, 31, 91, 37, 31, 23, 18, 95, 6, 69, 85, 28, 76, 15, 21, 91, 45, 44, 18, 78, 5, 20, 80, 36, 90, 1, 44, 65, 100, 18, 54, 85, 47, 18, 59, 61, 33, 72, 55, 22, 39, 46, 14]


In [23]:
#Sample
sample = random.sample(x,k=10)
print(sample)

[54, 44, 39, 46, 15, 80, 22, 61, 9, 47]


In [24]:
#Standard deviation(std)
s1 = [60,59,61,58,62]
s2 = [45,75,90,30,60]
print(stats.mean(s1))
print(stats.mean(s2))
print(stats.stdev(s1))
print(stats.stdev(s2))

60
60
1.5811388300841898
23.717082451262844


In [25]:
# std: speard of data around mean

# formula
- variance = sum(xi-xmaen)**2
- std = variance**2/N

##### Data Distribution
- uniform dist
- normal dist
- standard normal dist
- left skewed dist
- right skewed dist
etc.

In [26]:
import random
import statistics as stats

In [27]:
x = []
for i in range(50):
    x.append(random.gauss(mu = 100, sigma =10))

In [28]:
print(x)

[100.00083706559778, 95.96626705427039, 98.38067569738033, 86.55577823781385, 112.39882736052351, 96.31180165199373, 89.20633148469153, 114.62793867047192, 88.1397845052536, 86.56933611400237, 110.62162885253703, 98.80354461455609, 75.2430268650858, 114.38179826300536, 81.61062516335684, 87.18381896802191, 108.06063734332822, 91.49638410761168, 89.44675789175066, 91.75196099225924, 96.64473273120402, 108.29066969098643, 104.87411362591052, 93.58108890059779, 102.00484240860615, 109.25923310957471, 95.36386589986392, 84.75205455386578, 103.01220512504953, 106.07073132270791, 111.07378400594322, 100.70572134336507, 110.73548472023036, 89.16951271716837, 86.88763135443322, 99.5562355481753, 94.27403512462526, 88.5620192132989, 102.7905498587917, 93.2214292668773, 101.97647908820981, 73.90649308610813, 89.7872807803393, 89.49959157830014, 99.63254116200878, 95.46005231631435, 112.31576570789235, 109.2196468057108, 88.98202999445508, 96.78533208584265]


In [29]:
print(stats.mean(x))
print(stats.median(x))
print(stats.mode(x))

97.10305828059937
96.47826719159887
100.00083706559778


In [35]:
x = []
for i in range(50):
    x.append(random.uniform(10,90))
    
l1 = []
l3 = []
l4 = []
for i in x:
    if(i>=0 and i<40):
        l1.append(i)
    elif(i>=40 and i<70):
        l3.append(i)
    else:
        l4.append(i)
        
print(len(l1))
print(len(l3))
print(len(l4))

22
18
10


In [92]:
# central limit theorem
x = []
for i in range(100):
    x.append(random.randint(1,100))
print(x)

[38, 17, 12, 3, 2, 90, 57, 18, 12, 30, 59, 85, 66, 33, 86, 64, 44, 53, 50, 40, 11, 22, 27, 93, 1, 44, 91, 75, 8, 4, 17, 61, 7, 85, 54, 68, 65, 69, 22, 75, 15, 46, 15, 79, 48, 36, 39, 2, 85, 60, 81, 12, 90, 96, 40, 82, 52, 56, 88, 61, 80, 11, 98, 56, 7, 33, 98, 59, 83, 91, 23, 84, 20, 46, 77, 10, 18, 72, 87, 71, 29, 43, 4, 76, 7, 98, 98, 50, 64, 88, 76, 26, 10, 47, 90, 83, 77, 17, 90, 3]


In [77]:
s1 = random.sample(x,k = 10)
print(stats.mean(s1))

45.2


In [78]:
s2 = random.sample(x,k = 10)
print(stats.mean(s2))

46.9


In [79]:
s3 = random.sample(x,k = 10)
print(stats.mean(s3))

49.8


In [80]:
s4 = random.sample(x,k = 10)
print(stats.mean(s4))

32.3


In [81]:
s5 = random.sample(x,k = 10)
print(stats.mean(s5))

60.3


In [82]:
s6 = random.sample(x,k = 10)
print(stats.mean(s6))

45.3


In [83]:
s7 = random.sample(x,k = 10)
print(stats.mean(s7))

37.6


In [84]:
s8 = random.sample(x,k = 10)
print(stats.mean(s8))

34


In [85]:
s9 = random.sample(x,k = 10)
print(stats.mean(s9))

51.4


In [86]:
s10 = random.sample(x,k = 10)
print(stats.mean(s10))

41.2


In [87]:
lst = [45.2,46.9,49.8,32.3,60.3,45.3,37.6,34,51.4,41.2]

In [88]:
print(stats.mean(lst))
print(stats.median(lst))
print(stats.mode(lst))

44.4
45.25
45.2


In [93]:
z = []
for i in range(10):
    s = random.sample(x,k =10)
    z.append(stats.mean(s))

In [94]:
print(stats.mean(z))
print(stats.median(z))
print(stats.mode(z))

51.39
51.05
40.5


In [1]:
import numpy as np

In [4]:
np.__version__

'1.21.5'

In [8]:
a = np.array([10,20,30])
print(type(a))

<class 'numpy.ndarray'>


In [10]:
print(a)
print(a.dtype)

[10 20 30]
int32


In [11]:
a = np.array([10,20,30,40.5])
print(type(a))
print(a)
print(a.dtype)

<class 'numpy.ndarray'>
[10.  20.  30.  40.5]
float64


In [12]:
a = np.array([10,20,30,40.5,"hello"])
print(type(a))
print(a)
print(a.dtype)

<class 'numpy.ndarray'>
['10' '20' '30' '40.5' 'hello']
<U32


In [13]:
a = np.array([10,20,30,40.5], dtype=np.int32)
print(type(a))
print(a)
print(a.dtype)

<class 'numpy.ndarray'>
[10 20 30 40]
int32


In [14]:
a = np.array([10,20,30,40.5,"hello"],dtype=np.int32)
print(type(a))
print(a)
print(a.dtype)

ValueError: invalid literal for int() with base 10: 'hello'

In [18]:
a=np.arange(1,10,2)
print(a)

[1 3 5 7 9]


In [19]:
a=np.arange(1,20,2.5)
print(a)

[ 1.   3.5  6.   8.5 11.  13.5 16.  18.5]


In [4]:
a=np.arange(1,100,5)
print(a)


[ 1  6 11 16 21 26 31 36 41 46 51 56 61 66 71 76 81 86 91 96]
20


In [9]:
a=np.arange(1,100,12)
print(a)
print(len(a))

[ 1 13 25 37 49 61 73 85 97]
9
